-- Drop and recreate maps table

DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(255) NOT NULL,
lon FLOAT,
lat FLOAT,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
