-- Drop and recreate pins table

DROP TABLE IF EXISTS pins CASCADE;

CREATE TABLE pins(
id SERIAL PRIMARY KEY NOT NULL,
title VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
picture VARCHAR(255),
lon INTEGER NOT NULL,
lat INTEGER NOT NULL,
map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);
